# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
   - cron: "0 0 * * *"
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ["weekly-builds"]

    steps:
      - name: Run a multi-line script
        run: |
          git clone https://github.com/FreeCAD/FreeCAD
          touch version.txt
          cd FreeCAD
          echo "commit-number: " >> ../version.txt
          git rev-list --count master >> ../version.txt
          echo "\nbranch: " >> ../version.txt
          git branch >> ../version.txt
          echo "\ndate: " >> ../version.txt
          date +"Year: %Y, Month: %m, Day: %d" >> ../version.txt
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: version.txt
          tag: ${{ matrix.tag }}
          overwrite: true
          file_glob: true
