# This is a basic workflow to help you get started with Actions

name: source_creation

# Controls when the workflow will run
on:
  schedule:
   - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ["weekly-builds"]
        branch: ["master"]

    steps:
      - name: Run a multi-line script
        run: |
          git clone https://github.com/FreeCAD/FreeCAD
          touch freecad_version.txt
          cd FreeCAD
          git checkout ${{ matrix.branch }}
          echo "commit-number: " >> ../freecad_version.txt
          git rev-list --count master >> ../freecad_version.txt
          echo "branch: " >> ../freecad_version.txt
          git branch >> ../freecad_version.txt
          echo "date: " >> ../freecad_version.txt
          date +"%Y/%m/%d">> ../freecad_version.txt
          git archive ${{ matrix.branch }} -o ../freecad_source.tar.gz
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: freecad*
          tag: ${{ matrix.tag }}
          overwrite: true
          file_glob: true
